### ISSUE TITLE
use TextAppearance to replace textColor, textSize, textStyle, etc

### ISSUE THREAD

**Issue by peacepassion** [robinhood/ticker#10]
support attribute android:textAppearance.

**Comment by jinatonic** [comment]
Good point, this would be useful to have. I'll investigate for the next release.

**Comment by BjarnBronsveld** [comment]
Bump; but textStyle="bold" is not working, can this be added too?

**Comment by danh32** [comment]
@BjarnBronsveld we're currently only reading `textSize` and `textColor` from the `textAppearance`. Can you open a new ticket requesting we add `textStyle`? I'm afraid this comment will get lost in the shuffle.
