### ISSUE TITLE
2.0.1 setPreferredScrollingDirection doesn't call 

### ISSUE THREAD

**Issue by denzsbs** [robinhood/ticker#101]
i am using version 2.0.1 but setPreferredScrollingDirection or app:ticker_preferredScrollingDirection doesn't call.  

 😁 why? am i missing something ?  

can someone inform me

**Comment by jinatonic** [comment]
looks like that commit didn't make it into 2.0.1. I'll do a 2.0.2 release sometime today.

**Comment by jinatonic** [comment]
I released `2.0.2`, it should be available shortly.
