### ISSUE TITLE
Support for Paint Flags

### ISSUE THREAD

**Issue by Ekalips** [robinhood/ticker#107]
Hello.
It'll be pretty good to add a support for `setPaintFlags(int)` method.

This will be extremely useful for setting fake bold flag (when your typeface doesn't have bold variation)  

Best Regards

**Comment by jinatonic** [comment]
Thanks for the suggestions. There is currently a field on `TickerView` that you can use to customize if you want.

```protected final Paint textPaint = new TextPaint(Paint.ANTI_ALIAS_FLAG);```

But I'll throw up a PR to add support for this.
