### ISSUE TITLE
Enable sorting of stocks in portfolio based on different metrics

### ISSUE THREAD

**Issue by BrandonLiang** [robinhood/ticker#122]
Hi,

**This issue most likely doesn't belong here but I couldn't find any Robinhood repository that is related to mobile app/web ui display. So please feel free to redirect this issue to the appropriate personnel.** 

Feature Request: add a sorting feature/page in user's account so that a user can sort the owned stocks based on different metrics (e.g.: % gain of all time, $ gain of all time, % gain of 1w, etc). This would help the user understand the performances of the owned stocks based on different metrics in different time frame.

**Comment by jinatonic** [comment]
thanks for the feedback. I passed it to the team :)
