### ISSUE TITLE
wrap_content doesn't work when set value from a larger number to a smaller number

### ISSUE THREAD

**Issue by BaronZ** [robinhood/ticker#15]
wrap_content doesn't work when set value from a larger number to a smaller number.
lets assume || is a textview, change number from 1234567 to 123, the width of the textview turns out like below

|1234567|
|123　　   |

What I think it supposed to be is like below

|1234567|
|123|

**Comment by peacepassion** [comment]
I also found this problem. I would like to post a gif later.

**Comment by BaronZ** [comment]
@peacepassion urs looks fine

**Comment by jinatonic** [comment]
Ah, I see the problem. We should be re-measuring after the animation completes (we don't re-measure for each frame of the animation) but that doesn't seem to be happening for you. I'll investigate this. Thanks for reporting!
