### ISSUE TITLE
animation listener

### ISSUE THREAD

**Issue by BaronZ** [robinhood/ticker#16]
would u pls add a method to add animation listener?

**Comment by jinatonic** [comment]
May I ask you what's your use-case for needing an animation listener on `TickerView`?

**Comment by BaronZ** [comment]
umm, i think i need the progress listener, i need to scale my view every 1000.
eg: if the number is 1000, 2000, 11000, i need to scale my view

**Comment by jinatonic** [comment]
I don't think this library does that. For example, going from "1" to "10000" it won't count and have animation updates when the number reaches "1000". It instead animates directly from "1" to "10000". 

If you want to perform some custom action every 1000, you can have your custom logic set the appropriate numbers on the `TickerView` at certain intervals, and then you'll have full control over what you do at each interval.
