### ISSUE TITLE
Add Animation Listener

### ISSUE THREAD

**Issue by imidhuntv** [robinhood/ticker#23]
I have seen that you have closed #16 .
But I think we should add an animation listener to that. In my case I'm showing ticker in red/green colour depending on whether the change is positive/negative. But after the animation I want to make it black again.
This may be the case with some of the people who wants to use TickerView.
Thank you for this awesome library. :)

**Comment by jinatonic** [comment]
Ah, very valid use-case, and it's something that we considered implementing within Robinhood app as well. Thank you for the input!

**Comment by imidhuntv** [comment]
Thank you Jin Cao.
