### ISSUE TITLE
Auto resize

### ISSUE THREAD

**Issue by BjarnBronsveld** [robinhood/ticker#35]
Hello,

I would love a feature where it possible to dynamically change the textSize to fit into the view? Can't use my resizable textview anymore with this library.

**Comment by jinatonic** [comment]
Sorry for the delay, this ticket got lost on my tracker. 

We allow for you to set the text size on `TickerView`, is that not sufficient? You can detect when the `TickerView` exceeds your view bounds and resize accordingly.
