### ISSUE TITLE
Shadow on numbers

### ISSUE THREAD

**Issue by sydneyitguy** [robinhood/ticker#38]
It seems there's no way to add shadow on numbers because
`TickerView` extends `View` instead of `TextView`.

I tried with `TickerTextAppearance`, but it didn't work.
What would be the best way to implement the text shadow?

**Comment by jinatonic** [comment]
yeah unfortunately not all `TextView` attributes are supported at the moment. I can't guarantee that I'll get around to implementing this, but if you want to work on it feel free to submit a PR.
