### ISSUE TITLE
 Ticking of "$" and "." in currency string

### ISSUE THREAD

**Issue by hiteshsahu** [robinhood/ticker#39]
While testing ticker for simple incremental values using below code snippet,

   ```
 float totalBill= 0;

    public void onUpdate() {
        final String currencyFloat = Float.toString((++totalBill) * 100);
        tickerView.setText("$" + currencyFloat.substring(0, Math.min(digits, currencyFloat.length())));
    }

```

I found that $ and . are also ticking along with changed digit. Ticker should avoid ticking nondigital characters.

**Comment by jinatonic** [comment]
This is currently working as intended. However, the algorithm to compute how to change from one text to another should try to preserve as much of the original text as possible so the leading `$` symbol should never change.

**Comment by paulvidal** [comment]
Hi @hiteshsahu 

Just had the same problem while using the library but solved it by changing the character list given :)

You need to set instead of 

```
tickerView.setCharacterList(**TickerUtils.getDefaultNumberList()**);
```

this

```
tickerView.setCharacterList(**TickerUtils.getDefaultListForUSCurrency()**);
```

and the $ and . characters won't tick :)
