### ISSUE TITLE
Support gravity attribute

### ISSUE THREAD

**Issue by Jawnnypoo** [robinhood/ticker#4]
You can see that the width of TickerView does a weird jump when you have the width set to `wrap_content` and you go from a longer string, such as "August" to a shorter string, such as "July". It will appear normal at first, with the "July" text appearing centered within within the view. When you then set the text to a similarly short string, such as "June", you will see the text jump from being center aligned to being left aligned. 

I am going to investigate this further and see if I can find a solution.

**Comment by jinatonic** [comment]
Ah, good catch! I realized that I haven't tested much with `wrap_content`, but I would imagine that this bug happens when we re-measure and re-layout as a result of setting new target text we don't take the current width into account. I'll take a look today.

**Comment by jinatonic** [comment]
Did a quick investigation, this behavior is a result of us not supporting a `gravity` attribute at the moment. Without a `gravity`, we always try to center the text (which doesn't quite make sense when the width is `wrap_content`). If you comment out the code to left justify the text with `wrap_content` then this is no longer an issue.

**Comment by Jawnnypoo** [comment]
Wow, quick turnaround! Thanks guys
