### ISSUE TITLE
Support for Android Databinding library?

### ISSUE THREAD

**Issue by kevcgrant** [robinhood/ticker#41]
It would be useful to be able to make use of the databinding library to update the ticker, to follow MVVM design principles. Is there any way to do this currently?

e.g:
```
<com.robinhood.ticker.TickerView
            android:id="@+id/opponent_score_ticker"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textAppearance="@style/text_large"
            android:text="@{viewModel.number}"/>
```

**Comment by jinatonic** [comment]
Hello,

Unfortunately I am unsure how the data binding library integrates with custom views. If the framework doesn't do it automatically then we currently do not support it.

**Comment by mcassiano** [comment]
@kevcgrant you can just create your own binding adapter :)

**Comment by kevcgrant** [comment]
@mcassiano thanks! That is what I ended up doing.
