### ISSUE TITLE
Auto resize

### ISSUE THREAD

**Issue by mahi05** [robinhood/ticker#45]
Please add a feature to Auto resize texts when texts exceeds tickerView bounds.
Like, I have to give fix width to tickerView and manage its text size according to its width. Then how can I manage it?

**Comment by jinatonic** [comment]
You can just set the textview width to `match_parent`, and it will auto adjust the drawing bounds accordingly. Or `wrap_content` will be fine but when the width of the text changes you might see some jank. To overcome this, you can call `TickerView.setAnimateMeasurementChange`.
