### ISSUE TITLE
Digital transform errors

### ISSUE THREAD

**Issue by 348026593** [robinhood/ticker#46]
when transform 15233 to 9151 or reverse，in the LevenshteinUtils，method computeColumnActions has mistake，turn the number to 152335 & 915

**Comment by 348026593** [comment]
if u have the same problem!    u can try this method:  TickerView.setText(10000,false); then transform the number you want with animation.  use this method can solve this problem.

**Comment by jinatonic** [comment]
Ah, thanks for filing the bug! I'll take a look at this tomorrow and throw up a fix.

**Comment by jinatonic** [comment]
Great catch, I found a bug where I'm incorrectly assuming that the max number of changes is capped at `max(oldLength, newLength)`. Fix incoming.

**Comment by 348026593** [comment]
ok，i will try when i am not busy！ thank u！！！
