### ISSUE TITLE
How can I add border for each number text.

### ISSUE THREAD

**Issue by bigbigpeng3** [robinhood/ticker#53]
I want to add border for each number ?

just like this view:

[https://github.com/bigbigpeng3/XCDemoSet/blob/master/app/src/main/java/com/pengzhangdemo/com/myapplication/widget/StrokeTextView.java](https://github.com/bigbigpeng3/XCDemoSet/blob/master/app/src/main/java/com/pengzhangdemo/com/myapplication/widget/StrokeTextView.java)

result image just like this:

[https://github.com/bigbigpeng3/XCDemoSet/blob/master/borderText.png](https://github.com/bigbigpeng3/XCDemoSet/blob/master/borderText.png)

I'm try to make different paint for it.but the result is not what I expected.

**Comment by jinatonic** [comment]
This requires adding support for custom draw logic which we currently don't have. I'm going to track the custom drawing work in #52 and close this issue.

**Comment by bigbigpeng3** [comment]
Thanks,I'm just work this out.Here is the code:

    `protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);

        canvas.save();

        realignAndClipCanvasForGravity(canvas);

        // canvas.drawText writes the text on the baseline so we need to translate beforehand.
        canvas.translate(0f, metrics.getCharBaseline());
        
        borderPaint = new Paint(textPaint);
        borderPaint.setColor(getContext().getResources().getColor(R.color.ticker_border_color));
        borderPaint.setStrokeWidth(4);
        borderPaint.setAntiAlias(true);
        borderPaint.setFakeBoldText(true);
       // borderPaint.setTextSize(30f);
        borderPaint.setStyle(Paint.Style.STROKE);
        
        textPaint.setAntiAlias(true);
        borderPaint.setTypeface(TextTypeUtils.getRoundTypeFace(getContext()));
        textPaint.setTypeface(TextTypeUtils.getRoundTypeFace(getContext()));
        
        columnManager.draw(canvas, textPaint, borderPaint);
        
        canvas.restore();
    }`

Result just like this:

[https://github.com/bigbigpeng3/XCDemoSet/blob/master/borderText.png](https://github.com/bigbigpeng3/XCDemoSet/blob/master/borderText.png)


Thanks Again!

Another question,how can I reverse the scroll direction ?  ...

**Comment by bigbigpeng3** [comment]
ok I'm solved reverse problem .

in TickerColumn.class

    `if (isReversed){

            // Drawing the bottom character here might seem counter-intuitive because we've been
            // computing for the bottom character this entire time. But the bottom character
            // computed above might actually be above the baseline if we interrupted a previous
            // animation that gave us a positive additionalDelta.
            drawText(canvas, textPaint, characterList, bottomCharIndex - 1,
                    bottomDelta + charHeight);

            // Draw the corresponding top and bottom characters if applicable
            drawText(canvas, textPaint, characterList, bottomCharIndex + 1,
                    bottomDelta - charHeight);
        }else {

            // Draw the corresponding top and bottom characters if applicable
            drawText(canvas, textPaint, characterList, bottomCharIndex + 1,
                    bottomDelta - charHeight);

            drawText(canvas, textPaint, characterList, bottomCharIndex - 1,
                    bottomDelta + charHeight);
        }`

define boolean isReversed in TickerColumn.class .

Done with it.
