### ISSUE TITLE
Support for unsupported: single digits to 10, 10 digits to another, and so on

### ISSUE THREAD

**Issue by lovetomatoo** [robinhood/ticker#57]
Support for unsupported: single digits to 10, then 10 digits to another, and so on

**Comment by jinatonic** [comment]
Hello,

Can you provide an example of what you mean? We do support arbitrary number of digits.

**Comment by lovetomatoo** [comment]
I mean: for example a number 1314,the digits scroll from 0 to 9,after digits scroll to 9,ten digits begain scroll...,and so on    just like clock,only after Second hand move to 60,Minute hand begain to move.

I want to know this lib can support  my requirements ?

**Comment by jinatonic** [comment]
unfortunately that is not supported by this library as we don't support wrap-around scrolling.
