### ISSUE TITLE
Disappearing characters

### ISSUE THREAD

**Issue by jinatonic** [robinhood/ticker#6]
Repro:
- Slow down animation.
- Start with a short string (e.g. "1234")
- Continuously set target to a longer string (e.g. "12345") before the animation completes.
- Observe that some characters start popping up mid-frame rather than smoothly scroll from top/bottom.

**Comment by jinatonic** [comment]
I think I observed this behavior on the Nexus 4 emulator.

**Comment by Perry-RU** [comment]
I haven't taken a deep look at the repo code but it does seem as though many of these issues only occur when a change has occurred before the animation has completed. That might be a nice place to start and perhaps put a safe guard patch up to protect against this.

**Comment by jinatonic** [comment]
This is fixed by #47
