### ISSUE TITLE
Change the view bounds to match the parent

### ISSUE THREAD

**Issue by Tokimu** [robinhood/ticker#65]
Is it possible to change the view bounds of the ticker so it matches the parent? The problem is that i can see animation starts just a little above the the ticker, not from the top of the view. i have set ticker to match the parent and gravity to center, the ticker pop up in the center but the view doesn't match the parent, more like wrap content.

**Comment by jinatonic** [comment]
Sorry for the late reply. I'm not too sure of the problem you are describing. Is the width or height not being set to match_parent? A video demonstrating the effect would be awesome.

**Comment by Tokimu** [comment]
Next week i will try to post the video. Anyway i was trying to set the ticker in a cardView, i set match_parent and centerInParent=true for it, unfortunately the dropping numbers didn't drop from the edge of the cardView (like i expected) but from the bounds of the ticker.
