### ISSUE TITLE
Request: Add isCharacterListSet() to API.

### ISSUE THREAD

**Issue by Domochevsky** [robinhood/ticker#85]
Hey,
as the title says, I'd like to see the function **isCharacterListSet()** added to the TickerView, so that can be dynamically set once it's required(, instead of hoping I remembered to initialize it beforehand or get Thrown out ">_> ).

Coding-wise, given what I've seen, this would likely be a simple null check on the _characterList_ field.

**Comment by naturalwarren** [comment]
That seems like a pretty reasonable request to me.
