### ISSUE TITLE
Scroll animation from bottom to top

### ISSUE THREAD

**Issue by SreekanthMekala** [robinhood/ticker#86]
Hello Team, Now scroll text happening top to bottom scrolling after change text, How do i change from Bottom to Top?

**Comment by jinatonic** [comment]
You can simply inverse the character list to scroll from bottom to top.

e.g. with a character list of "0123456789", animating from 0 to 9 will scroll top to bottom. However, if the character list is "9876543210", animating from 0 to 9 will scroll bottom to top.
