### ISSUE TITLE
Prevent Animation recycler view scroll

### ISSUE THREAD

**Issue by ghost** [robinhood/ticker#98]
This librery working fine.
but i need to prevent animation from adapter item when recycler view scoll.

**Comment by NickM-27** [comment]
I also have this issue, not sure how to prevent it when recyclerview is scrolling

**Comment by jinatonic** [comment]
I'm not sure what you guys mean, you want to prevent the ticker animation from happening when it's inside a scrolling recyclerview? that's not possible since ticker doesn't know what type of parent it's housed in, it's up to the recyclerview to somehow disable animation when it's scrolling.

**Comment by NickM-27** [comment]
I solved this problem by setting animation duration to 0 when scrolling, seems to work great

**Comment by jinatonic** [comment]
nice great workaround!
