### ISSUE TITLE
Set number range  

### ISSUE THREAD

**Issue by AshikAzeez** [robinhood/ticker#99]
How can i set number range in view like max 1000

**Comment by jinatonic** [comment]
I don't understand, you can just specify in your own code to not set a number above 1000?

**Comment by AshikAzeez** [comment]
Ok,i mean like this in Edit text and Textview propertie `android:maxLength="12" `

**Comment by jinatonic** [comment]
belated, I don't quite see a use-case for `maxLength` for Ticker. I mostly don't want to replicate attributes from `TextView` unless it makes sense.
